#ifndef MOO_HELP_SECTIONS_H
#define MOO_HELP_SECTIONS_H

#define HELP_SECTION_APP_LICENSE "ch04.html"
#define HELP_SECTION_DIALOG_FIND "index.html"
#define HELP_SECTION_DIALOG_FIND_FILE "index.html"
#define HELP_SECTION_DIALOG_FIND_IN_FILES "index.html"
#define HELP_SECTION_DIALOG_REPLACE "index.html"
#define HELP_SECTION_FILE_SELECTOR "index.html"
#define HELP_SECTION_PREFS_ACCELS "index.html"
#define HELP_SECTION_PREFS_DIALOG "ch01s01.html"
#define HELP_SECTION_PREFS_FILE "ch01s03.html"
#define HELP_SECTION_PREFS_FILE_SELECTOR "ch01s06.html"
#define HELP_SECTION_PREFS_FILTERS "ch01s05.html"
#define HELP_SECTION_PREFS_GENERAL "ch01s02.html"
#define HELP_SECTION_PREFS_LANGS "ch01s04.html"
#define HELP_SECTION_PREFS_PLUGINS "ch01s01.html"
#define HELP_SECTION_PREFS_USER_TOOLS "ch03s01.html"
#define HELP_SECTION_PREFS_VIEW "ch01s01.html"
#define HELP_SECTION_USER_TOOLS "ch03.html"

#endif /* MOO_HELP_SECTIONS_H */
