#ifndef EGG_SM_CLIENT_MANGLE_H
#define EGG_SM_CLIENT_MANGLE_H

#define egg_sm_client_xsmp_get_type _moo_egg_sm_client_xsmp_get_type
#define egg_sm_client_win32_get_type _moo_egg_sm_client_win32_get_type
#define egg_sm_client_osx_get_type _moo_egg_sm_client_osx_get_type

#define egg_sm_client_get_type _moo_egg_sm_client_get_type
#define egg_sm_client_get_option_group _moo_egg_sm_client_get_option_group
#define egg_sm_client_register _moo_egg_sm_client_register
#define egg_sm_client_get _moo_egg_sm_client_get
#define egg_sm_client_is_resumed _moo_egg_sm_client_is_resumed
#define egg_sm_client_get_state_dir _moo_egg_sm_client_get_state_dir
#define egg_sm_client_get_config_prefix _moo_egg_sm_client_get_config_prefix
#define egg_sm_client_set_restart_command _moo_egg_sm_client_set_restart_command
#define egg_sm_client_will_quit _moo_egg_sm_client_will_quit
#define egg_sm_client_end_session _moo_egg_sm_client_end_session
#define egg_sm_client_save_state _moo_egg_sm_client_save_state
#define egg_sm_client_quit_requested _moo_egg_sm_client_quit_requested
#define egg_sm_client_quit_cancelled _moo_egg_sm_client_quit_cancelled
#define egg_sm_client_quit _moo_egg_sm_client_quit
#define egg_sm_client_xsmp_new _moo_egg_sm_client_xsmp_new
#define egg_sm_client_dbus_new _moo_egg_sm_client_dbus_new
#define egg_sm_client_win32_new _moo_egg_sm_client_win32_new
#define egg_sm_client_osx_new _moo_egg_sm_client_osx_new
#define egg_sm_client_dummy_new _moo_egg_sm_client_dummy_new
#define egg_sm_client_get_mode _moo_egg_sm_client_get_mode
#define egg_sm_client_get_state_file _moo_egg_sm_client_get_state_file
#define egg_sm_client_set_mode _moo_egg_sm_client_set_mode

#endif /* EGG_SM_CLIENT_MANGLE_H */
