AM_CPPFLAGS += -I$(srcdir)/plugins/support

plugins_sources +=				\
	plugins/support/moocmdview.h		\
	plugins/support/moocmdview.cpp		\
	plugins/support/mooeditwindowoutput.h	\
	plugins/support/mooeditwindowoutput.cpp	\
	plugins/support/moolineview.cpp		\
	plugins/support/moolineview.h		\
	plugins/support/moooutputfilter.cpp	\
	plugins/support/moooutputfilter.h
