moo_sources +=			\
    moocpp/fileutils.h		\
    moocpp/fileutils.cpp	\
    moocpp/gobjptr.h		\
    moocpp/gstr.h		\
    moocpp/gstr.cpp		\
    moocpp/moocpp.h		\
    moocpp/regex.h		\
    moocpp/regex.cpp		\
    moocpp/util.h


