if MOO_BUILD_CTAGS
plugins_sources +=			\
	plugins/ctags/readtags.c	\
	plugins/ctags/readtags.h	\
	plugins/ctags/readtags-mangle.h	\
	plugins/ctags/ctags-plugin.c	\
	plugins/ctags/ctags-doc.c	\
	plugins/ctags/ctags-doc.h	\
	plugins/ctags/ctags-view.c	\
	plugins/ctags/ctags-view.h
endif MOO_BUILD_CTAGS
