xdgmime_sources =		\
	xdgmime/xdgmimealias.c	\
	xdgmime/xdgmimealias.h	\
	xdgmime/xdgmime.c	\
	xdgmime/xdgmimecache.c	\
	xdgmime/xdgmimecache.h	\
	xdgmime/xdgmimeglob.c	\
	xdgmime/xdgmimeglob.h	\
	xdgmime/xdgmime.h	\
	xdgmime/xdgmimeint.h	\
	xdgmime/xdgmimeicon.c	\
	xdgmime/xdgmimeicon.h	\
	xdgmime/xdgmimemagic.c	\
	xdgmime/xdgmimemagic.h	\
	xdgmime/xdgmimeparent.c	\
	xdgmime/xdgmimeparent.h

#if MOO_OS_WIN32
#EXTRA_DIST += $(xdgmime_sources)
#else
moo_sources += $(xdgmime_sources)
#endif
